// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4FZw66b1Drn7bOvqc3L1Snecgzdnr7RQ',
    appId: '1:855129774231:web:6087384244caee52c4b1d2',
    messagingSenderId: '855129774231',
    projectId: 'riverpod-state-mangment',
    authDomain: 'riverpod-state-mangment.firebaseapp.com',
    storageBucket: 'riverpod-state-mangment.firebasestorage.app',
    measurementId: 'G-SXS08W7ZPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHWiYpaokzKA-jHtJLE8io7UnoJ4acXw',
    appId: '1:855129774231:android:ecec3855c025d104c4b1d2',
    messagingSenderId: '855129774231',
    projectId: 'riverpod-state-mangment',
    storageBucket: 'riverpod-state-mangment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDekOQ3uwJHwc8EsexFE8rcZ2IRky_UVNU',
    appId: '1:855129774231:ios:e7164f3feb00f806c4b1d2',
    messagingSenderId: '855129774231',
    projectId: 'riverpod-state-mangment',
    storageBucket: 'riverpod-state-mangment.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDekOQ3uwJHwc8EsexFE8rcZ2IRky_UVNU',
    appId: '1:855129774231:ios:e7164f3feb00f806c4b1d2',
    messagingSenderId: '855129774231',
    projectId: 'riverpod-state-mangment',
    storageBucket: 'riverpod-state-mangment.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4FZw66b1Drn7bOvqc3L1Snecgzdnr7RQ',
    appId: '1:855129774231:web:e829f93dc6aaf6ddc4b1d2',
    messagingSenderId: '855129774231',
    projectId: 'riverpod-state-mangment',
    authDomain: 'riverpod-state-mangment.firebaseapp.com',
    storageBucket: 'riverpod-state-mangment.firebasestorage.app',
    measurementId: 'G-G00CYD000G',
  );
}
